// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://clhwmjlxwxnhbewvurvr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNsaHdtamx4d3huaGJld3Z1cnZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNjIwNjMsImV4cCI6MjA2MjgzODA2M30.sMsQ4ceXvjItXe6Qcs2Mr-K5DFQSxUkPyH72hEdv_zc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);